import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  Container: {
    alignItems: 'center',
    flex: 1,
  },
  HeaderText: {
    fontSize: 30,
    fontWeight: 'bold',
    color: 'black',
    paddingVertical: 50,
  },
  box: {
    width: '100%',
    alignItems: 'center',
    backgroundColor: 'white',
    paddingTop: 30,
    borderBottomRightRadius: 30,
    borderBottomLeftRadius: 30,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.5,
    shadowRadius: 4,
    elevation: 5,
  },
  FormContainer: {
    width: '100%',
    paddingHorizontal: 25,
    marginTop: 35,
  },
  FormInput: {
    borderColor: '#477ED0',
    borderWidth: 1,
    width: 'auto',
    borderRadius: 5,
    fontSize: 20,
    paddingHorizontal: 15,
    color: 'black',
    backgroundColor: '#ffff',
  },
  cardPhoto: {
    backgroundColor: '#E4EBF3',
    borderRadius: 15,
    paddingHorizontal: 25,
    paddingVertical: '15%',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.5,
    shadowRadius: 4,
    elevation: 5,
    top: 0,
    position: 'absolute',
    width: '100%',
  },
  imageDisplay: {
    position: 'absolute',
    padding: 60,
    bottom: 10,
    backgroundColor: '#D9D9D9',
    borderRadius: 100,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.5,
    shadowRadius: 4,
    elevation: 5,
  },
});
